-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["ast1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -85.5, 181.5  ,  -154, 92  ,  -47, -283  ,  -46, -283  ,  93.5, -179.5  ,  191.5, 97.5  ,  145, 186  ,  21.5, 276.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -47, -283  ,  -154, 92  ,  -186.5, -16.5  ,  -160.5, -234.5  ,  -126.5, -273.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   179, 7.5  ,  -11.5, 257  ,  85, -133.5  ,  173, -82.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -11.5, 257  ,  179, 7.5  ,  212.5, 46  ,  210, 116.5  ,  181, 203.5  ,  87.5, 286  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   85, -133.5  ,  -11.5, 257  ,  -72.5, 219  ,  -212, -4.5  ,  -225, -114.5  ,  -43, -299.5  ,  16.5, -282  ,  57.5, -251  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -43, -300.5  ,  -224, -104.5  ,  -209, -163.5  ,  -146, -242.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -225, -114.5  ,  -43, -300.5  ,  -43, -299.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -225, -114.5  ,  -43, -300.5  ,  -224, -104.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3.5, 171  ,  -235, -84.5  ,  -205, -92.5  ,  56.5, -95  ,  134.5, 45  ,  137, 140.5  ,  109, 171.5  ,  51, 188.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   134.5, 45  ,  56.5, -95  ,  113.5, -34  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   56.5, -95  ,  -205, -92.5  ,  -104, -185.5  ,  -103, -185.5  ,  -45, -164.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast4"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   75.5, 148  ,  3.5, 201  ,  -146.5, 78  ,  -155, -21.5  ,  -23, -191.5  ,  47.5, -194  ,  93, -172.5  ,  160, -57.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -78, 178.5  ,  -146.5, 78  ,  3.5, 201  ,  -56.5, 201  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3.5, 201  ,  75.5, 148  ,  32.5, 194  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28.5, -212  ,  -27.5, -212  ,  -23, -191.5  ,  -155, -21.5  ,  -100, -144.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -155, -21.5  ,  -146.5, 78  ,  -159, 28.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast5"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, 131.5  ,  -97.5, 75  ,  -119.5, -53  ,  -119.5, -153  ,  43, -154.5  ,  92, -104.5  ,  121.5, 55  ,  102, 132.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -119.5, -153  ,  -119.5, -53  ,  -145.5, -109  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -119.5, -153  ,  -78, -173.5  ,  -77, -173.5  ,  43, -154.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast6"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = .2, friction = 0, bounce = .9, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25.5, -137.5  ,  -25.5, -136.5  ,  -117.5, 77.5  ,  -149.5, 12.5  ,  -119.5, -106.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = .2, friction = 0, bounce = .9, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   128.5, -5.5  ,  121, 45  ,  -117.5, 77.5  ,  -25.5, -136.5  ,  99, -103  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = .2, friction = 0, bounce = .9, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1, 142  ,  -117.5, 77.5  ,  121, 45  ,  68, 121  }
                    }
                    
                    
                    
		}
		
		, 
		["ast7"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   115.5, 55.5  ,  -51, -135  ,  85.5, -90.5  ,  222, 1  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -208.5, 34.5  ,  -143, -69  ,  -52, -135  ,  -51, -135  ,  -48, 134  ,  -88, 132  ,  -180, 92  ,  -209.5, 64.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   72.5, 100.5  ,  -48, 134  ,  -51, -135  ,  115.5, 55.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast8"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, 85.5  ,  105.5, 71.5  ,  117, 98  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -160, -74  ,  -106.5, -130.5  ,  -105.5, -130.5  ,  133, -70  ,  67.5, 85.5  ,  -41, 116  ,  -91, 113  ,  -176, 26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   142, 54  ,  105.5, 71.5  ,  150, -11  ,  162, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   150, -11  ,  133, -70  ,  160, -29  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   105.5, 71.5  ,  67.5, 85.5  ,  133, -70  ,  150, -11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   133, -70  ,  -105.5, -130.5  ,  44, -126  ,  146.5, -85.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast9"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -122, 76.5  ,  -56, -71.5  ,  23, -165.5  ,  127, 72.5  ,  82, 128.5  ,  44.5, 145  ,  -124.5, 144  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   127, 72.5  ,  23, -165.5  ,  108.5, -79  ,  143, -17.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   23, -166.5  ,  23, -165.5  ,  -56, -71.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast10"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   134, -19  ,  85, 98  ,  59.5, 130.5  ,  -68.5, -180.5  ,  -67.5, -180.5  ,  74.5, -140.5  ,  143.5, -97.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -101, 130  ,  -145, -15  ,  -116, -124  ,  -68.5, -180.5  ,  59.5, 130.5  ,  4.5, 158.5  ,  -71, 160  }
                    }
                    
                    
                    
		}
		
		, 
		["ast11"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -93.5, -82  ,  -8, -132.5  ,  -7, -132.5  ,  104, -95.5  ,  129.5, 14  ,  114, 70.5  ,  -84, 127.5  ,  -141.5, 9  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -84, 127.5  ,  114, 70.5  ,  3, 157.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   104, -95.5  ,  -7, -132.5  ,  73, -120.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast12"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -78.5, 148  ,  -143, 30.5  ,  -152, -59.5  ,  66.5, -184  ,  67.5, -184  ,  105, -39.5  ,  118, 129.5  ,  12, 192.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   66.5, -184  ,  -152, -59.5  ,  -116, -144.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   118, 129.5  ,  105, -39.5  ,  106, -49.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast13"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3.5, -210  ,  -5.5, -269  ,  12.5, -294  ,  42, -302.5  ,  43, -302.5  ,  131, -291.5  ,  101, -199.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   191.5, -335  ,  189, -315.5  ,  131, -291.5  ,  43, -302.5  ,  141, -358.5  ,  171, -357.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -105, -253.5  ,  -158.5, -211  ,  -193, -222.5  ,  -164.5, -291  ,  -97, -302.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148.5, -123  ,  -158.5, -211  ,  -100.5, -199  ,  -86.5, -153  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -194, -222.5  ,  -193, -222.5  ,  -240.5, -172  ,  -240, -209.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -294.5, -55  ,  -240.5, -172  ,  -193, -222.5  ,  -158.5, -211  ,  -148.5, -123  ,  -151.5, -73  ,  -172.5, -38  ,  -230, -22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -240.5, -172  ,  -294.5, -55  ,  -305.5, -93  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8.5, -311  ,  -38.5, -325  ,  -37.5, -354  ,  -17, -358.5  ,  -16, -358.5  ,  23, -345.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -187.5, 74  ,  -253, 98.5  ,  -265, 76.5  ,  -227, 28.5  ,  -226, 28.5  ,  -191, 34.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -304.5, 127  ,  -318.5, 111  ,  -265, 76.5  ,  -253, 98.5  ,  -254.5, 127  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -265, 76.5  ,  -318.5, 111  ,  -311.5, 82  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -118, 250.5  ,  -182, 217.5  ,  -192, 162.5  ,  -152, 131.5  ,  -112, 130.5  ,  -49, 185.5  ,  -50, 231.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -192, 162.5  ,  -182, 217.5  ,  -208.5, 231  ,  -235, 218.5  ,  -248.5, 191  ,  -239.5, 163  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -153, 131.5  ,  -152, 131.5  ,  -192, 162.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   52, 331.5  ,  108, 259.5  ,  253, 231.5  ,  254, 231.5  ,  278.5, 259  ,  259, 303.5  ,  94, 373.5  ,  47.5, 361  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   47, 298.5  ,  -9.5, 285  ,  -18.5, 267  ,  6, 246.5  ,  7, 246.5  ,  53, 262.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -92, 315.5  ,  -102.5, 298  ,  -81, 276.5  ,  -80, 276.5  ,  -53, 289.5  ,  -45, 317.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast14"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   10.5, -242.5  ,  -27.5, -247.5  ,  -33.5, -267.5  ,  -16, -277  ,  -15, -277  ,  14.5, -269.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   3.5, -159.5  ,  -3.5, -208.5  ,  19, -230  ,  20, -230  ,  99, -222  ,  83, -154  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   148.5, -252.5  ,  99, -222  ,  20, -230  ,  110, -276  ,  139, -271  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -80.5, -196.5  ,  -123, -170  ,  -147, -172  ,  -126.5, -224.5  ,  -78, -235  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148, -172  ,  -147, -172  ,  -123, -170  ,  -187.5, -129.5  ,  -186.5, -159.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -175, -17  ,  -222, -38  ,  -234.5, -74.5  ,  -187.5, -129.5  ,  -123, -170  ,  -116, -91  ,  -129, -33  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -116, -91  ,  -123, -170  ,  -72.5, -148.5  ,  -65.5, -119.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   211, 231  ,  75, 287  ,  37.5, 279.5  ,  80, 202  ,  154, 180  ,  204, 179  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   153, 180  ,  154, 180  ,  80, 202  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -146, 124  ,  -142, 167  ,  -178, 171  ,  -184, 125  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -146, 124  ,  -125, 106  ,  -124, 106  ,  -33, 150  ,  -39.5, 178.5  ,  -88, 193  ,  -142, 167  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -69, 112  ,  -33, 150  ,  -124, 106  ,  -96, 98  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -208, 59  ,  -193, 75  ,  -207, 100  ,  -236, 97  ,  -237.5, 60.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -193, 75  ,  -208, 59  ,  -164, 16  ,  -163, 16  ,  -146.5, 28.5  ,  -145.5, 58.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   16, 189  ,  17, 189  ,  46.5, 213.5  ,  25, 235  ,  -14.5, 205.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -66.5, 246.5  ,  -74, 221  ,  -47, 218  ,  -46, 218  ,  -37.5, 245.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -47, 218  ,  -74, 221  ,  -57, 209  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

