-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["ast3"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4.5, 172  ,  -233.5, -84  ,  -203, -93.5  ,  56, -95.5  ,  112.5, -35  ,  134.5, 44  ,  109.5, 171  ,  62, 188.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   109.5, 171  ,  134.5, 44  ,  138, 140.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   56, -95.5  ,  -203, -93.5  ,  -104, -185.5  ,  -103, -185.5  ,  -45, -164.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast4"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   126.5, 49  ,  63.5, 165  ,  -148, 74.5  ,  -160, 4.5  ,  -100, -149.5  ,  -18.5, -193  ,  88, -176.5  ,  161.5, -55  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148, 74.5  ,  63.5, 165  ,  24.5, 199  ,  -53.5, 206  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   88, -176.5  ,  -18.5, -193  ,  51.5, -194  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -100, -149.5  ,  -27, -210.5  ,  -18.5, -193  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27, -211.5  ,  -27, -210.5  ,  -100, -149.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast5"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -119.5, -154  ,  -78, -173.5  ,  -77, -173.5  ,  43, -154.5  ,  92, -104.5  ,  -119.5, -53  ,  -145.5, -110  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, 131.5  ,  -92.5, 84  ,  -119.5, -53  ,  92, -104.5  ,  122.5, 65  ,  102, 132.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast6"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = .2, friction = 0, bounce = .9, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   128.5, -5.5  ,  111, 42  ,  -117.5, 77.5  ,  -25.5, -136.5  ,  99, -103  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = .2, friction = 0, bounce = .9, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25.5, -137.5  ,  -25.5, -136.5  ,  -117.5, 77.5  ,  -149.5, 12.5  ,  -119.5, -104.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = .2, friction = 0, bounce = .9, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -117.5, 77.5  ,  111, 42  ,  121, 45  ,  67.5, 119.5  ,  -1, 142  }
                    }
                    
                    
                    
		}
		
		, 
		["ast7"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -208.5, 34.5  ,  -142.5, -69.5  ,  -52, -135  ,  116, 55  ,  -37, 131  ,  -77, 134  ,  -180, 92  ,  -209.5, 64.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -37, 131  ,  116, 55  ,  73.5, 100.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -52, -135  ,  -51, -135  ,  196, 8  ,  116, 55  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   226.5, 7.5  ,  196, 8  ,  -51, -135  ,  75, -96  }
                    }
                    
                    
                    
		}
		
		, 
		["ast8"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, 85.5  ,  105, 71  ,  117, 97  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -160, -74  ,  -106.5, -130.5  ,  -105.5, -130.5  ,  -61.5, 119.5  ,  -91, 113  ,  -176, 26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   142, 54  ,  105, 71  ,  150, -11  ,  162, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   150, -11  ,  133, -69  ,  160, -29  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   105, 71  ,  67.5, 85.5  ,  -61.5, 119.5  ,  -105.5, -130.5  ,  44, -126  ,  133, -69  ,  150, -11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   133, -69  ,  44, -126  ,  145.5, -85.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast9"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -122, 76.5  ,  -56, -71.5  ,  23, -165.5  ,  127, 72.5  ,  81, 129.5  ,  42.5, 145  ,  -126.5, 145  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   127, 72.5  ,  23, -165.5  ,  114, -71.5  ,  143, -17.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   23, -166.5  ,  23, -165.5  ,  -56, -71.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast10"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   130, -11  ,  92, 85  ,  61.5, 126.5  ,  -115.5, -123.5  ,  -68.5, -180.5  ,  -67.5, -180.5  ,  96.5, -129.5  ,  140.5, -101.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -115.5, -123.5  ,  61.5, 126.5  ,  7, 156  ,  -71, 160  ,  -94, 139  ,  -145, -15  }
                    }
                    
                    
                    
		}
		
		, 
		["ast11"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -93.5, -79  ,  -9, -132.5  ,  -8, -132.5  ,  129.5, 11  ,  121.5, 60  ,  5, 158.5  ,  -80, 128.5  ,  -141.5, 12  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   129.5, 11  ,  -8, -132.5  ,  62, -124.5  ,  107, -98.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast12"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   14, 191.5  ,  -35.5, 180  ,  -81, 142.5  ,  71, -179.5  ,  105, -53.5  ,  116, 125.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   71, -180.5  ,  71, -179.5  ,  -81, 142.5  ,  -141, 35.5  ,  -151, -64.5  ,  -112, -147.5  }
                    }
                    
                    
                    
		}
		
		, 
		["ast13"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   14, -313.5  ,  -34, -319.5  ,  -42.5, -348  ,  -20, -359.5  ,  -19, -359.5  ,  20.5, -349  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   24, -198.5  ,  0, -215.5  ,  -3.5, -275  ,  40, -302.5  ,  41, -302.5  ,  127.5, -286  ,  104, -199.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   192.5, -327  ,  127.5, -286  ,  41, -302.5  ,  149, -359.5  ,  178.5, -354  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -105.5, -253  ,  -157.5, -211  ,  -193, -222.5  ,  -164, -291.5  ,  -96.5, -301  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148.5, -123  ,  -157.5, -211  ,  -99, -198.5  ,  -86.5, -152  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -194, -222.5  ,  -193, -222.5  ,  -240.5, -173  ,  -244.5, -202  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -294, -54.5  ,  -240.5, -173  ,  -193, -222.5  ,  -157.5, -211  ,  -148.5, -123  ,  -151.5, -73  ,  -172.5, -38  ,  -230, -22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -240.5, -173  ,  -294, -54.5  ,  -305.5, -93  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -318.5, 112  ,  -308, 78.5  ,  -307, 78.5  ,  -247, 96.5  ,  -275, 133.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -198, 85.5  ,  -247, 96.5  ,  -261.5, 73  ,  -213, 21.5  ,  -184.5, 49  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -247, 96.5  ,  -307, 78.5  ,  -261.5, 73  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -237, 216.5  ,  -188, 160.5  ,  -140, 126.5  ,  -183, 217.5  ,  -210, 231.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -188, 160.5  ,  -237, 216.5  ,  -248.5, 188  ,  -236.5, 161  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -140, 126.5  ,  -139, 126.5  ,  -100, 136.5  ,  -46.5, 188  ,  -53, 233.5  ,  -111, 251.5  ,  -183, 217.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -53, 233.5  ,  -46.5, 188  ,  -38.5, 207  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -3, 250.5  ,  -2, 250.5  ,  54.5, 292  ,  26, 303.5  ,  -2, 291.5  ,  -18, 266.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   54.5, 292  ,  -2, 250.5  ,  38, 249.5  ,  58.5, 272  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -95, 312.5  ,  -106, 295.5  ,  -87, 277.5  ,  -86, 277.5  ,  -58, 284.5  ,  -48.5, 319  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   271, 298.5  ,  105.5, 261  ,  209, 230.5  ,  210, 230.5  ,  269, 237.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   49.5, 335  ,  105.5, 261  ,  271, 298.5  ,  88, 375.5  ,  50.5, 364  }
                    }
                    
                    
                    
		}
		
		, 
		["ast14"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   10.5, -242.5  ,  -27, -248  ,  -33.5, -267.5  ,  -16, -276  ,  -15, -276  ,  15, -270  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8, -156  ,  -5.5, -194.5  ,  4.5, -222.5  ,  69, -247  ,  70, -247  ,  97.5, -220.5  ,  78.5, -153.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   97.5, -220.5  ,  70, -247  ,  122, -277  ,  148.5, -251.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -115.5, -92.5  ,  -122, -161  ,  -74, -150  ,  -70, -113  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -91, -236  ,  -90, -236  ,  -75.5, -206.5  ,  -122, -161  ,  -137.5, -175.5  ,  -128, -223  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -187.5, -129.5  ,  -137.5, -175.5  ,  -122, -161  ,  -115.5, -92.5  ,  -122, -43  ,  -144, -22  ,  -213, -32  ,  -234.5, -74.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -137.5, -175.5  ,  -187.5, -129.5  ,  -187, -159  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -200.5, 56.5  ,  -196.5, 77.5  ,  -196.5, 97.5  ,  -235.5, 96.5  ,  -243.5, 68.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148.5, 62.5  ,  -196.5, 77.5  ,  -200.5, 56.5  ,  -200.5, 55.5  ,  -167, 17  ,  -143.5, 33.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -152, 126  ,  -91, 193  ,  -186.5, 160.5  ,  -181.5, 122.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -108, 98  ,  -76, 107  ,  -91, 193  ,  -152, 126  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -51.5, 185.5  ,  -91, 193  ,  -76, 107  ,  -75, 107  ,  -32, 153  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   209, 230  ,  73, 288  ,  82, 200  ,  169, 177  ,  170, 177  ,  208.5, 184.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   82, 200  ,  73, 288  ,  36, 277  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8.5, 189.5  ,  33, 195  ,  46, 212  ,  26.5, 234.5  ,  -14.5, 207.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, 195  ,  34, 195  ,  46, 212  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -62, 249  ,  -82.5, 226.5  ,  -50, 216  ,  -49, 216  ,  -32.5, 242.5  }
                    }
                    
                    
                    
		}
        ,

        ["ast11Small"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 0, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   1, 37  ,  -21, 27  ,  -33, 8  ,  -32, -11  ,  -4, -31.5  ,  -3, -31.5  ,  22, -27  ,  31, 10  }
                    }
                    
                    
                    
        }
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

